#!/usr/bin/env bash
# Figure 2 from "Self Consistency in Reference Frames", Blewitt 2003
# 
# The purpose of this figure is to illustrate
# different reference frames isomorphic wrt degree
# one deformation.
#
# Description from the paper:
# Degree one deformations in various frames, generated by
# eq. 16. A cross section of the Earth is shown where the
# load moment points along the Earth's axis towards the 
# North Pole (top of the figure). Filled circles show stations
# on the Earth's surface (solid line) prior to deformation.
# Open circles show stations on the Earth's surface (red here)
# after deformation for each indicated frame. By definition,
# each frame origin (+) remains stationary during mass
# redistribution. Within each frame, CM is displaced from the
# origin to a new location (x).

# Compute Earth's surface after deformation
compute_deformation() {
    gmt math observation_$1.dat -i0-3 -o0,1 \
        -C0 2 COL ADD -C1 3 COL ADD = deformation_$1.dat
}

# Compute lines joining stations prior to and post deformation
compute_quiver() {
    # The math for column three is simply a way of setting
    # the column to a constant value. I am not good enough
    # at shell to do this the right way yet.
    paste observation_$1.dat deformation_$1.dat | \
        gmt math STDIN -i0,1,3,3,2,2 -o0-3 \
        -C3 5 COL HYPOT -1 GT 0.75 MUL -C2 4 COL ATAN2D = quiver_$1.dat
}

# Plot the deformation for a specified frame
plot_deformation() {
    # Compute position of deformed points
    compute_deformation $1
    compute_quiver $1

    # Uncomment to see direction of motion from
    # observation to and through deformed points
    # gmt plot quiver_$1.dat -Sv0.25c -W1p,gray@20

    # Plot deformed points
    gmt plot deformation_$1.dat -Wthin,red
    gmt plot deformation_$1.dat -Sc5p -Wthin,red -Gwhite

    # Plot observed points
    gmt plot observation_$1.dat -Wthin
    gmt plot observation_$1.dat -Sc5p -Gblack

    # Plot center of reference frame
    echo "0 0 0.2" | gmt plot -S+ -Wthin
    # Plot center of the CM reference frame
    echo "0 ${2} 0.2" | gmt plot -Sx -Wthin,red
    # Plot labels for each reference frame
    echo "0 0 ${3}" | gmt text -D0c/-0.4c -F+f16p,Times-Roman+jTC
    echo "0 0 ${4}" | gmt text -D0c/-0.9c -F+f8p,Times-Roman+jTC
}

gmt begin figure02 png
    # Top row
    gmt subplot begin 1x2 -Fs7/7 -R-7/7/-7/7 -Jx1/1 -B+n -M-0.5
        gmt subplot set 0,0
        plot_deformation ce 1 "CE Frame" "Center of Mass of Solid Earth"
        gmt subplot set 0,1
        plot_deformation cm 0 "CM Frame" "Center of Mass of Entire Earth"
    gmt subplot end

    # Bottom row
    gmt subplot begin 1x3 -Fs7/7 -R-7/7/-7/7 -Jx1/1 -B+n -X-3 -Y-5.5 -M-0.5
        gmt subplot set 0,0
        plot_deformation cf 1.021 "CF Frame" "Center of Surface Figure"
        gmt subplot set 0,1
        plot_deformation cl 0.887 "CL Frame" "Center of Lateral Surface Figure"
        gmt subplot set 0,2
        plot_deformation ch 1.290 "CH Frame" "Center of Height Surface Figure"
    gmt subplot end

    # Clean up
    rm -f quiver_* deformation_*
gmt end
